# All Reference: 
# github actions 教學- part1 : Ref: https://www.youtube.com/watch?v=a-EiC_Ll3EM
# github actions 教學: Ref: https://github.com/twtrubiks/github-actions-tutorial
# Setup by python: Ref: https://github.com/actions/setup-python
# Heroku 可以參考這篇，但我沒測試出來 Ref:https://javascript.plainenglish.io/deploy-to-heroku-with-github-actions-a890044a620f

# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # using post way to build the github action!
  # post url : https://api.github.com/repos/davidjan76324/github_action/dispatches
  # Ref: https://godleon.github.io/blog/DevOps/learn-GitHub-Action-1/
  #repository_dispatch:
  #  types: [build]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_my_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt
      # using ${{ github.event.client_payload.[key name] }} to get the post params infomation!!
      #- run: echo name is ${{ github.event.client_payload.name }}, age is ${{ github.event.client_payload.age }}

      # - name: Run My python code
      #   run: python test.py

      # # Runs a single command using the runners shell
      # - name: Check Django project
      #   run: cd mysite; python manage.py check
  deploy:
    # --- Deploy to self-hosted
    runs-on: self-hosted
    needs: build_my_project
    steps:
    - name: Download build job
      uses: actions/checkout@v3
      
    - name: Deploy to my server
      run: |
        cd mysite
        RUNNER_TRACKING_ID="" && nohup python3 manage.py runserver &
    
    #--- 複製檔案到 AWS EC2
    runs-on: ubuntu-latest
    needs: build_my_project
    steps:
      - name: Check the files
        uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EVENT_TARGET: ${{ secrets.EC2_VENV_TARGET_DIR }}
        run: lsb_release -a
      # run: |
      #   cd mysite
      #   ls
      #   python3 manage.py runserver &
      #   echo 'done runserver'


      # Send eamil
      # - name: Send mail
      #   if: always()
      #   uses: dawidd6/action-send-mail@v2
      #   with:
      #     # mail server settings
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     # user credentials
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     # email subject
      #     subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      #     # email body as text
      #     body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      #     # comma-separated string, send email to
      #     to: david_jan76324@hotmail.com
      #     # from email name
      #     from: John Doe
